name = "hono-api-starter-develop"
main = "src/index.ts"
compatibility_date = "2024-10-29"
compatibility_flags = [ "nodejs_compat" ]

[vars]
CORS_ALLOWED_ORIGINS = "https://hono-api-starter-develop.pages.dev"


[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[env.prod]
name = "hono-api-starter"

[env.prod.vars]
CORS_ALLOWED_ORIGINS = "https://hono-api-starter.pages.dev"


[env.prod.ai]
binding = "AI"

[env.prod.observability]
enabled = true
head_sampling_rate = 1